# https://github.com/actions/deploy-pages#usage
name: Nuxt.js CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Clean install dependencies
        run: |
          rm -rf package-lock.json node_modules
          pnpm install --force

      - name: Build project
        run: pnpm generate

      - name: Ensure unique artifact name
        run: echo "nuxtjs-build-${{ github.run_id }}" > artifact-name.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxtjs-build
          path: .output/public

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: nuxtjs-build
